arb-dir: lib/l10n
template-arb-file: app_en.arb
output-localization-file: app_localizations.dart
supported-locales:
  - en
  - es
  - fr
  - de
  - it
  - pt
  - ru
  - ja
  - ko
  - zh
  - hi
  - ar
  - bn
  - ur
  - fa
  - tr
  - vi
  - th
  - nl
  - sv