name: myapp
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  firebase_core: ^4.2.0
  provider: ^6.1.5+1
  flutter_chat_ui: ^2.9.1
  flutter_chat_types: ^3.6.2
  uuid: ^4.4.0
  http: ^1.2.2
  speech_to_text: ^7.3.0
  flutter_tts: ^4.0.2
  shared_preferences: ^2.2.3
  intl: ^0.20.2
  cached_network_image: ^3.3.1
  connectivity_plus: ^7.0.0
  google_fonts: ^6.2.1
  image_picker: ^1.1.2
  google_generative_ai: ^0.4.7
  firebase_ai: ^3.4.0
  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  mockito: ^5.5.1 # Reverted to previously working version
  firebase_core_platform_interface: ^6.0.2

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/fonts/
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
