// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// A placeholder class for Firebase options.
///
/// You should replace this with your actual Firebase project configuration.
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBYdDhWm_pDupJBUTUPI06chZZR3F_06IM',
    appId: '1:47108552775:web:84bd04311d21aa441b5962',
    messagingSenderId: '47108552775',
    projectId: 'dart-editer',
    authDomain: 'dart-editer.firebaseapp.com',
    storageBucket: 'dart-editer.firebasestorage.app',
    measurementId: 'G-N4NTNWJWMZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCMMTc9SF0IF9vMF97fQye-TttqoBtqWLs',
    appId: '1:47108552775:android:51ee882c277b43711b5962',
    messagingSenderId: '47108552775',
    projectId: 'dart-editer',
    storageBucket: 'dart-editer.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDMZduHSOsSyzO47EyBG949vDCg6IJgJNc',
    appId: '1:47108552775:ios:595bc460d4430e281b5962',
    messagingSenderId: '47108552775',
    projectId: 'dart-editer',
    storageBucket: 'dart-editer.firebasestorage.app',
    iosBundleId: 'com.example.myapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDexdmONGWm53q2S_SVVAxc2K4Yue_xbgM',
    appId: 'YOUR_APP_ID',
    messagingSenderId: 'YOUR_MESSAGING_SENDER_ID',
    projectId: 'YOUR_PROJECT_ID',
    storageBucket: 'YOUR_STORAGE_BUCKET',
    iosClientId: 'YOUR_IOS_CLIENT_ID',
    iosBundleId: 'YOUR_IOS_BUNDLE_ID',
  );
}
